version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secret-key-here
      - DEBUG=False
      - DATABASE_URL=postgresql://postgres:password@db:5432/jorp
    depends_on:
      - db
    volumes:
      - .:/app
      - static_volume:/app/staticfiles

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=jorp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume: 