# Generated by Django 5.2.4 on 2025-07-26 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vocabulary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='base_form',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='grammar_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='pos',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='vocabulary',
            unique_together={('user', 'korean_word', 'base_form')},
        ),
    ]
