# Generated by Django 5.2.4 on 2025-07-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_alter_vocabulary_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korean_word', models.CharField(max_length=100, unique=True)),
                ('english_translation', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
    ]
