# Generated by Django 5.2.4 on 2025-07-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_hovertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='hover_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='last_5_durations',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='total_hover_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='HoverTracking',
        ),
    ]
