# Generated by Django 5.2.4 on 2025-07-30 12:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0005_vocabulary_hover_count_vocabulary_last_5_durations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vocabulary',
            unique_together={('user', 'korean_word')},
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='base_form',
        ),
    ]
