# Generated by Django 5.2.4 on 2025-07-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0006_alter_vocabulary_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
