# Generated by Django 5.2.4 on 2025-07-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0007_vocabulary_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='grammars',
            field=models.ManyToManyField(blank=True, related_name='vocabularies', to='vocab.grammar'),
        ),
    ]
