# Generated by Django 5.2.4 on 2025-07-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0009_migrate_grammar_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='added_via_know_rest',
            field=models.BooleanField(default=False),
        ),
    ]
