# Generated by Django 5.2.4 on 2025-07-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0010_vocabulary_added_via_know_rest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='added_via_know_rest',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='retention_rate',
            field=models.FloatField(default=0.1),
        ),
    ]
