# Generated by Django 5.2.4 on 2025-07-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0011_remove_vocabulary_added_via_know_rest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaltranslation',
            name='english_translation',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='globaltranslation',
            name='korean_word',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
