# Generated by Django 5.2.4 on 2025-08-05 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0012_alter_globaltranslation_english_translation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='last_recall_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='recall_failures',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='recall_successes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='globaltranslation',
            name='english_translation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='globaltranslation',
            name='korean_word',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
