# Generated by Django 5.2.4 on 2025-08-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0013_add_recall_fields'),
        ('vocab', '0013_vocabulary_last_recall_update_and_more'),
    ]

    operations = [
    ]
