# Generated by Django 5.2.4 on 2025-08-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0014_merge_20250805_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='alpha_prior',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='beta_prior',
            field=models.FloatField(default=1.0),
        ),
    ]
