# Generated by Django 5.2.4 on 2025-09-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0016_wordencounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='encounter_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='WordEncounter',
        ),
    ]
