# Generated by Django 5.2.4 on 2025-09-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0017_vocabulary_encounter_count_delete_wordencounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='in_vocab',
            field=models.BooleanField(default=False),
        ),
    ]
